### ISSUE TITLE
Problem with filenames containing german umlauts

### ISSUE THREAD

**Issue by daooze** [clawsoftware/clawPDF#1]
When creating a PDF from a file whose filename contains umlauts, those characters are replaced with '?'.

In my example I created a file with Notepad whose name is 'Umlauts Test ae-ä oe-ö ue-ü sz-ß Ae-Ä Oe-Ö Ue-Ü.txt'. When printing to clawPDF the suggested title is 'Umlauts Test ae-? oe-? ue-? Ae-? Oe-? Ue-?'.

**Comment by clawsoftware** [comment]
Thank you for the hint! I added unicode support for filenames (v0.8.4).

**Comment by daooze** [comment]
Works great, thank you for the quick solution.
