### ISSUE TITLE
Prints completely wrong colors

### ISSUE THREAD

**Issue by hansworzt** [clawsoftware/clawPDF#15]
Installed clawPDF, printed the PDF test documents, which look fine.
However, printing one of my own PDFs (created by Miktex) went completely wrong; all the colors are wrong, e.g. the text is printed in red! When I choose Color Model : CMYK, then the colors appear washed-out. How to fix this?

**Comment by ylaroye** [comment]
I have the same problem. Sometimes the text is printed in red!

**Comment by clawsoftware** [comment]
Fixed with GS10 update

**Comment by LeenHatem** [comment]
@clawsoftware Hello, I am using the old version of clawPDF, and I need to keep using it for a while before updating. I noticed that the "red problem" occurs for some users and for some pdf's only, have you figured out what devices it works on without this problem?  Thank you.

**Comment by clawsoftware** [comment]
@LeenHatem The color profile was not always applied correctly, which is why this error could occur.
