### ISSUE TITLE
Doesn't work with space-containing user profiles

### ISSUE THREAD

**Issue by TheChief5055** [clawsoftware/clawPDF#16]
> 2020-02-20 14:04:07.3421 [Error] clawSoft.clawPDF.App.App_OnStartup: There was an error while starting clawPDF System.IO.FileNotFoundException: Файл 'C:\Users\The' не найден.
Имя файла: 'C:\Users\The'

It's actually 'C:\Users\The Chief\'.

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
