### ISSUE TITLE
Saves to wrong printer profile directory path

### ISSUE THREAD

**Issue by vineykhera** [clawsoftware/clawPDF#17]
If i understood profile settings correctly, its not considering auto save path correctly based on printer.

**Comment by vineykhera** [comment]
I created 3 printers and 3 separate profiles, pointing to different auto save dir path. 

Lets say:
printer name - printer auto save path
 Printer A      - C:\print\dirA
 Printer B      - C:\print\dirB
 Printer C      - C:\print\dirC

If I print to Printer A, it saves files under C:\print\dirC rather than saving in C:\print\dirA for printerA.
Same with B.

**Comment by ad-d** [comment]
Yes there is definitely a problem with printer profiles, all printers just use the settings from the last changed profile sadly.  

I have two printers created clawPDF_Invoice (using Invoice profile and set to print using an Invoice background PDF file) and clawPDF_PO (using PO profile and set to print using a PO background PDF file).

If I print to clawPDF_PO I get the background I set for clawPDF_Invoice.  If I open up clawPDF_PO profile settings and make no changes other than click Save button then when I next print I get the correct background, this of course then messes up the background for clawPDF_Invoice which then displays the PO background.

Both printers get whatever the last saved settings were, they do not respect the profile settings listed.

Same results across Win7/10/Server 2019 and version 0.8.4 of course.

**Comment by clawsoftware** [comment]
Patched with version 0.8.6
