### ISSUE TITLE
larger print size

### ISSUE THREAD

**Issue by minajones** [clawsoftware/clawPDF#21]
Hi,
I'm trying to use this to creat pdfs for scientific posters.  right now the maximum size is 78.75 inches in either dimention.  Is there any way to increase this?

**Comment by clawsoftware** [comment]
This is currently already possible. If you need more sizes, you can tell me here. Thank you very much!

https://github.com/clawsoftware/clawPDF/wiki/(Custom)-Paper-Sizes

**Comment by ASRSim13** [comment]
right now the maximum size 2000 mm = 78.85 inches. We need a bigger size.
