### ISSUE TITLE
The application source not compiling

### ISSUE THREAD

**Issue by amit302** [clawsoftware/clawPDF#22]
Hi,

We tried to compile source code on IDE VS Version 19 but giving some error. We are not able to resolve it. Please find the attached error screenshots. Please help to resolve the issue.
![clawPDF_setup vdproj_error](https://user-images.githubusercontent.com/49816165/78504689-601f1d00-778c-11ea-91f7-b09e3504fb2a.gif)

**Comment by twooclock** [comment]
See issue #9

**Comment by christianpare** [comment]
You seem to be missing the C++ extensions.  I installed them and this error disappeared and I have been able to compile the binaries.

**Comment by alfredolopez80** [comment]
I have de same issue!!!
![image_2020-04-20_12-44-17](https://user-images.githubusercontent.com/20690133/80001428-597eee00-848c-11ea-86b5-cf7ac7963660.png)

Can i help us!!!

**Comment by twooclock** [comment]
See issue #9 :

"The Microsoft Visual Studio Installer Project extension needs to be added to VS 2019 before loading the project solution.

Extensions -> Manage Extensions
Find and Select -> Microsoft Visual Studio Installer Project
Restart VS 2019
Now open solution.

If solution was already opened and built, follow above steps, and after reopening VS 2019 and the clawPDF solution, select the clawPDF_setup project in solution explorer and execute a Project -> Reload"
