### ISSUE TITLE
Issue in clawmon\monitor\mon.cpp

### ISSUE THREAD

**Issue by twooclock** [clawsoftware/clawPDF#23]
Line 1290: 
WriteToIniFile(_T("0"), _T("**PinterName**"), m_szPrinterName, infpath);
shoud be
WriteToIniFile(_T("0"), _T("**PrinterName**"), m_szPrinterName, infpath);

This prevents usage of different profiles since profiles are determined via PrinterName. 
LastUsedProfile is always used.

**Comment by Axachi** [comment]
So will there bee anew update on the MSI with the changes for this soon?. As the latest one is from 2019... ???

**Comment by twooclock** [comment]
Sorry title refers to issue in mon.cpp. 
My change is in port.cpp wich is in ...\clawmon\monitor\ folder (see line 1290).
