### ISSUE TITLE
How to NOT open viewer after print auto-save

### ISSUE THREAD

**Issue by RajVrach** [clawsoftware/clawPDF#25]
Just want to print the PDF to auto-save to folder (this works).
**Do not want** the default PDF viewer to open after printing/auto-saving..could not find a setting in Profile.
So how do you do that?

**Comment by twooclock** [comment]
I checked the code and can't find it in user interface. As a workaround you can change OpenViewer setting in registry  under ...\ConversionProfiles\[Profile number]\OpenViewer.

**Comment by srliao** [comment]
@twooclock would you be able to point me to where the registry settings are? I'm looking under HKEY_CURRENT_USER\SOFTWARE and there's nothing there. Nothing under HKEY_LOCAL_MACHINE either.

Also how do we find out the [Profile Number]?

Thanks in advance!

**Comment by twooclock** [comment]
For default settings to be there open clawPDF, click "Applicaton settings" and click Save and also "Profile settings" click Save.

Search for clawPDF subkey. There are profile numbers under ConversionProfiles. Click profile number and check its Name (profile name). Should be more or less clear from here on...

**Comment by srliao** [comment]
Thank you. For anyone else looking for this, I found it under HKEY_USERS\<I'm guessing this is my user id>\SOFTWARE\clawSoft\clawPDF\Settings\ConversionProfiles

All the profiles are there so just take a look at the Profile Name and find the one you wish to change.

I'm guessing this is a per user basis setting. Not sure if there's a way to make this into a per machine setting.

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
