### ISSUE TITLE
silently save the pdf not posible. it always pops up the PDF.

### ISSUE THREAD

**Issue by ghost** [clawsoftware/clawPDF#27]
Wen selected automatic saving, there should be no popup with the PDF. 
JUST AUTOMATIC SAVING IN A FOLDER.
silently print PDF is not possible. there always pops up the file.
if you print 100 files this is very bad.

please add a silent mode

**Comment by twooclock** [comment]
See issue #25. Just edit the registry.

**Comment by Benchwork** [comment]
his issue has been resolved in the new version 0.8.5
![image](https://user-images.githubusercontent.com/7304823/224718428-2cd910ac-a2c8-4d9d-a5fc-7cfb111f2141.png)
just uncheck that box and it will not pop up

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
