### ISSUE TITLE
profiles and templates don't work (не работают профили и шаблоны )

### ISSUE THREAD

**Issue by 9993555** [clawsoftware/clawPDF#30]
Hi, thanks for the program but there is a problem:
I created 5 printers, 5 profiles for them, each profile should save a text file (TXT) to a certain folder, but this does not happen, I noticed which last profile saved this one and it works - that is, saving the profile that was last saved to a folder. It's the same with pdf.
<PrinterName>does not work in templates
Привет, спасибо за программу но есть проблемка:
Cоздал 5 принтеров, под них 5 профилей, каждый профиль должен сохранять в определенную папку текстовый файл (TXT) но это не происходит, заметил какой последний профиль сохранил такой и работает -  т.е. сохранение в папку того профиля который был последним сохранен. С pdf тоже самое.
В шаблонах не отрабатывает <PrinterName>

**Comment by twooclock** [comment]
See/fix issue #23 I believe it's related.
