### ISSUE TITLE
Error when openning clawPDF project with VS19

### ISSUE THREAD

**Issue by vinhphu56** [clawsoftware/clawPDF#31]
When I open the project file clawPDF.sln, I get this message:
This version of Visual Studio is unable to open the followig projects....
..\clawPDF_setup\clawPDF_setup.vdproj
I click OK, at the IDE screen of Solution Explorer show:
clawPDF_setup (incompatible)
        This project is incompatible with the current edition of Visual Studio

**Comment by twooclock** [comment]
You're missing VS extension "Microsoft Visual Studio Installer Projects". 
Go to Extensions/Manage Extensions and install it there, restart VS and reload the project.

**Comment by vinhphu56** [comment]
Thank you so much.

**Comment by vinhphu56** [comment]
Hi twooclock,
I still have the same problem.
![clawPDF error](https://user-images.githubusercontent.com/41869737/92312567-935a1800-ef87-11ea-919e-c4f273d3f7c1.jpg)
![vs2019 Project Installer](https://user-images.githubusercontent.com/41869737/92312569-96550880-ef87-11ea-987d-803b46fc780b.jpg)

**Comment by twooclock** [comment]
Have you restarted VS and reloaded the project? Do so...

**Comment by vinhphu56** [comment]
Yes, I restarted and open the project again.
