### ISSUE TITLE
Sometimes the printer is not working

### ISSUE THREAD

**Issue by shuang016** [clawsoftware/clawPDF#32]
I alr installed the printer and normally the printer can work.
However, sometimes I faced below issue:
1. the printer is not working when trigger it from any web browser or any printing page
2. **After reboot**, printer can work properly
3. **print test page** in application setting can work
4. No log file was saved
5. I check on the queue of the printer when I click **print**, it appear once and suddenly disappear from the queue list

Any possibility that can cause this issue and how to avoid that?

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
