### ISSUE TITLE
Disable auto-open file

### ISSUE THREAD

**Issue by mrkaban** [clawsoftware/clawPDF#33]
Hello, one of the visitors to the Russian-language site about free software wrote a comment on the description of ClawPDF. Here's a quote:
"_The program is wonderful. But I consider the impossibility to disable auto-opening of created files as a very big drawback._"

Is there really no way to turn off the automatic opening of the generated files?

Здравствуйте, один из посетителей русскоязычного сайта о свободном программном обеспечении написал комментарий к описанию ClawPDF. Вот цитата:
Программа замечательная. Но очень большим недостатков я считаю невозможность отключить автооткрытие созданных файлов

Действительно ли нет возможности отключить автоматическое открытие созданных файлов?

**Comment by twooclock** [comment]
See issue #25. Just edit the registry.
