### ISSUE TITLE
Cannot print image from a photo viewer app like Windows "Photos" app

### ISSUE THREAD

**Issue by mikeminhxi** [clawsoftware/clawPDF#36]
I tried printing files in Notepad, Word, Paint, websites.  They worked well with clawPDF printer.
But when I use Photos app or Paint3D to print out image files (.jpg, .png, .bmp) into PDF file, clawPDF printer cannot print out.
Can clawPDF supports to print image or anything by using new Windows 10 applications like Paint3D, Photos?
Will it work well as "Microsoft Print to PDF" printer?

**clawPDF worked with:**
_Paint_
![Paint Print window](https://user-images.githubusercontent.com/50949121/96767626-f81de480-1406-11eb-9e92-d4c0f394512d.png)

_Mouse Right-click menu then select Print_
![Mouse Right-click Print window](https://user-images.githubusercontent.com/50949121/96767661-05d36a00-1407-11eb-854c-040c18816cd3.png)

**Didn't work with:**
_Paint3D with new Windows 10 Print_
![Paint3D Print window](https://user-images.githubusercontent.com/50949121/96767671-08ce5a80-1407-11eb-8c50-9a8d90274089.png)

_Photos with new Windows 10 Print_
![Photos App Print window](https://user-images.githubusercontent.com/50949121/96767680-0b30b480-1407-11eb-9f4a-3e4bec131b34.png)

**Comment by gragonskies** [comment]
my bro. Have you solved this problem? How to solve this problem?

**Comment by mikeminhxi** [comment]
> 

Hi man, this problem was resolved long time ago.
I can't remember how to fix this problem.

**Comment by gragonskies** [comment]
Have you solved this problem？ I can't do it. Can you help me？thanks.

**Comment by christian1980nrw** [comment]
I can confim this bug. Windows Photo App is not printing with ClawPDF. Reason unknown.

**Comment by mikeminhxi** [comment]
> 

Sorry bro. Just checked again that our teams didn't fix this issue, and the customers who we worked for approved for this

**Comment by gragonskies** [comment]
I have fixed this issue. Set to local, not redirect.

**Comment by gragonskies** [comment]
I have fixed this issue. Set to local, not redirect.

**Comment by evilsin666** [comment]
Hi,
I am having this same problem when printing with clawPDF from microsoft store app. Could you please tell, how you solved the issue, it will be helpfull. Looking forward to hear from you.
Thanks

**Comment by evilsin666** [comment]
Also didn't understand the meaning of "Set to local, not redirect"

**Comment by evilsin666** [comment]
Solved the issue, set the attributes in PRINTER_INFO_2 structure to 0x00000041 instead of 0x00000002.
Thank you

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
