### ISSUE TITLE
Cannot change log level on clawmon printer port configuration 

### ISSUE THREAD

**Issue by grzyir1** [clawsoftware/clawPDF#37]
Hi, I have issue with clawmon port configuration. I need to change log level to 'all' but button ok is disabled.
Do you have any hints?

![Przechwytywanie](https://user-images.githubusercontent.com/32259073/99277393-0c9aa480-282e-11eb-8068-37b74430bfc3.JPG)

**Comment by clawsoftware** [comment]
Patched with version 0.8.6
