### ISSUE TITLE
a way to EMBED used fonts

### ISSUE THREAD

**Issue by t2t-paul** [clawsoftware/clawPDF#38]
is there a way to EMBED used fonts within the generated PDF files? perhaps a backdoor way / script if necessary (i see there is an option to subsequently "run script" within the profile settings interface)?

see screenshot attached - the source document contains a particular barcode font

![image](https://user-images.githubusercontent.com/3502343/101167751-50651a80-3632-11eb-8086-ccd57245f3bc.png)

however here is the generated PDF (via clawPDF) as viewed on a different computer - you can see the barcodes are not displayed correctly, presumably because that particular barcode font is not present on that other computer

![image](https://user-images.githubusercontent.com/3502343/101167821-6a066200-3632-11eb-8c37-efe2bbb9fb4a.png)

the fix for this issue is usually to force fonts to be embedded - e.g. see below the "embed all used fonts" setting within the profile manager from another pdf printer

![image](https://user-images.githubusercontent.com/3502343/101168024-b8b3fc00-3632-11eb-8e9b-5bae6da602a8.png)

PS. this is an outstanding program in my testing so far today, thanks

**Comment by berteh** [comment]
+1, pretty please. Make most of the layout effort of document author go to waste otherwise.

**Comment by bret-miller** [comment]
+1

**Comment by OBELIKS** [comment]
Save as PDF/X, that should fix this issue.

**Comment by t2t-paul** [comment]
> Save as PDF/X, that should fix this issue.

thanks for the suggestion but this made no difference, at least in my case: doing a spot of research i can see why you made the suggestion (the PDF/X standard means fonts should be embedded?) but just like normal "PDF" output the barcode font is not displayed. perhaps this means that there is a bug with the PDF/X output option? i also noticed the generated file size was around 100 times larger than using the other formats

i also tested the other PDF subsets that clawPDF has available, PDF/A-1b and PDF/A-2b: the first excluded the barcode altogether from the output, the second was just the same as the others. if it helps i have attached my own samples directly to this issue, including one using an alternate PDF printer and with fonts embedded

[UsingClawPDF_PDF.pdf](https://github.com/clawsoftware/clawPDF/files/6132789/UsingClawPDF_PDF.pdf)

[UsingNovaPDFWithEmbeddedFont.pdf](https://github.com/clawsoftware/clawPDF/files/6132790/UsingNovaPDFWithEmbeddedFont.pdf)

[UsingClawPDF_PDFAX.pdf](https://github.com/clawsoftware/clawPDF/files/6132791/UsingClawPDF_PDFAX.pdf)

[UsingClawPDF_PDFA2.pdf](https://github.com/clawsoftware/clawPDF/files/6132792/UsingClawPDF_PDFA2.pdf)

[UsingClawPDF_PDFA1.pdf](https://github.com/clawsoftware/clawPDF/files/6132793/UsingClawPDF_PDFA1.pdf)
