### ISSUE TITLE
Black box coming if printing Printer Spool EMF file

### ISSUE THREAD

**Issue by pradeepngupta** [clawsoftware/clawPDF#39]
hi,
I am getting an error for which request resolution.
I am using ClawPDF to Print a PDF file from an EMF file. Essential the emf file has the extention *.spl and has been picked from Printer Spool folder.
I am printing the spl file from SPLView (https://sourceforge.net/projects/splviewer/)
I am getting black rectangle boxes in some places of converted PDF. Don't know how to resolve this one. 
Attaching sample pdf showing the issue.
[abc.pdf](https://github.com/clawsoftware/clawPDF/files/5647007/abc.pdf)

Whereas if I am using Microsoft Print To PDF, the PDF is coming perfectly fine.
[ms_pdf.pdf](https://github.com/clawsoftware/clawPDF/files/5647011/ms_pdf.pdf)

Pl help in resolving this one.

Thanks
Pradeep Gupta

**Comment by clawsoftware** [comment]
I can't reproduce the behavior currently and would need an SPL file that is causing problems if the problem is still relevant.
