### ISSUE TITLE
Coolest virtual printer! Thank!

### ISSUE THREAD

**Issue by mrkaban** [clawsoftware/clawPDF#4]
Thank you very much for creating such a cool virtual printer under the GNU AGPL license. On my personal site about free software PDF Creator has long enjoyed great popularity, but it has a whole bunch of flaws that are constantly mentioned by our visitors.

One of them is any advertising stuff that is offered during installation. In your program this is not, THANKS!

The other of them, the lack of support for the TIF format, after one of the versions, it disappeared. Thank!

I bring a link to the description of your beautiful program on my website ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BE%D1%84%D0%B8%D1%81/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/clawpdf-%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D1%8C-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB.html)).

**Comment by den32ds** [comment]
Даже здесь континентсвободы.рф засветился. Круто. Спасибо за постоянно пополняемый список СПО.
Thanks for your virtual printer too.

**Comment by mrkaban** [comment]
Ведём поиск СПО везде где можно! Вам спасибо!

Успехов Вашему проекту! Большая просьба, не добавляйте рекламу, как в PDF Creator =)
