### ISSUE TITLE
Preserve the dimensions of the original printed file  

### ISSUE THREAD

**Issue by safinayah** [clawsoftware/clawPDF#40]
I'm using clawPDf to save a copy of the printed document, then print it using thermal receipt printer, but dimensions after conversion are too big, which makes the receipt cropped.  

If I print directly to the receipt printer without clawPDF, it print correct.

is there a way to preserve the original file dimensions when using clawPDF to convert to PDF file ?

**Comment by Moerup** [comment]
Also trying to achieve this, any one have got this working?

**Comment by clawsoftware** [comment]
This is a Windows print configuration rather than a problem with clawPDF. If it is an image, for example, in the "Print Images" window, the "Fit image to frame" setting can be disabled so that the image is not cropped.

**Comment by ipemusic-bp** [comment]
Did you solved your problem ? And how ? I run the same issue when I ask to clawPDF to print my document, it's cropped. But when I print the same document directly on the printer they are no problem.
