### ISSUE TITLE
How to change the printer name to a custom name and create installer for that name? 

### ISSUE THREAD

**Issue by kartikbathla** [clawsoftware/clawPDF#43]

**Comment by JungHo-K1m** [comment]
i have the same problem, is there anyone who solve this one?

**Comment by twooclock** [comment]
Usually you install clawPDF and then make custom printers form within. (Run clawPDF and then choose Program settings/Printers).

**Comment by JungHo-K1m** [comment]
After that, how can I create .msi or .exe file(installer) with changed name?
