### ISSUE TITLE
it prints nothing,I have tried another computer,but it can not work,forgive me for my poor English

### ISSUE THREAD

**Issue by tiandao123456** [clawsoftware/clawPDF#44]

**Comment by twooclock** [comment]
It works just fine! I opened in VS2019, built and even made a msi installer. Works like a charm!
Check code, debug and read previous issues. If you need help ask specific questions. 
"it prints nothing" is not very informative I'm afraid...
And don't apologize for your English, people who are willing to help don't care about languages.

**Comment by tiandao123456** [comment]
> It works just fine! I opened in VS2019, built and even made a msi installer. Works like a charm!
> Check code, debug and read previous issues. If you need help ask specific questions.
> "it prints nothing" is not very informative I'm afraid...
> And don't apologize for your English, people who are willing to help don't care about languages.

I installed the. MSI program and ran it to print PDF, but no PDF file was generated. It just ran but nothing was generated

**Comment by twooclock** [comment]
Now open Notepad (or any other text editor), type "IT WORKS!", select File/Print, choose ClawPDF printer and click Print button.
ClawPDF will ask you where to save resulting pdf file...

**Comment by tiandao123456** [comment]
yes，I have done this，but it did not work.&nbsp;It just runs, but it doesn't generate PDF files. I used a similar software before. It has pop-up errors and internal ghostscript errors.


------------------ Original ------------------
From: twooclock ***@***.***&gt;
Date: 周二,4月 20,2021 8:07 下午
To: clawsoftware/clawPDF ***@***.***&gt;
Cc: tiandao123456 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [clawsoftware/clawPDF] it prints nothing,I have tried another computer,but it can not work,forgive me for my poor English (#44)





 
Now open Notepad (or any other text editor), type "IT WORKS!", select File/Print, choose ClawPDF printer and click Print button.
 ClawPDF will ask you where to save resulting pdf file...

**Comment by twooclock** [comment]
What "pop-up errors and internal ghostscript errors." ? Post screenshots, paste errors...

**Comment by tiandao123456** [comment]
I'm sorry that I've gone home and didn't bring my computer. I can send you the screenshot tomorrow. Thank you very much for your help today. Thank you!

------------------ Original ------------------
From: twooclock ***@***.***&gt;
Date: 周二,4月 20,2021 8:46 下午
To: clawsoftware/clawPDF ***@***.***&gt;
Cc: tiandao123456 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [clawsoftware/clawPDF] it prints nothing,I have tried another computer,but it can not work,forgive me for my poor English (#44)





 
What "pop-up errors and internal ghostscript errors." ? Post screenshots, paste errors...

**Comment by tiandao123456** [comment]
> What "pop-up errors and internal ghostscript errors." ? Post screenshots, paste errors...

![image](https://user-images.githubusercontent.com/38206851/115490933-9cd38e80-a291-11eb-9c0f-7a72c1cfb930.png)
![image](https://user-images.githubusercontent.com/38206851/115491407-7f52f480-a292-11eb-8c2d-415368a016bd.png)
![image](https://user-images.githubusercontent.com/38206851/115491438-9265c480-a292-11eb-8af0-1189f0a21c0e.png)

As you can see, clawpdf doesn't produce anything and can't be found anywhere in the computer

**Comment by twooclock** [comment]
I tried your procedure and it works for me. I notice you have one more job waiting maybe that's interfering somehow? Go to printers and scanners (within windows) and check ClawPDF printer there. Use troubleshooting and try to print a test page.
Open ClawPDF and click Program settings (left button), click last section on the left (Errors) and see Error log (post it here if needed). Try and print test pages as well.

**Comment by tiandao123456** [comment]
I have tried to print test pages.The log is as follows:

2021-04-21 14:58:59.3107 [Error] clawSoft.clawPDF.Core.Jobs.GhostscriptJob.RunJobWork: There was an error while converting the Job C:\Users\涂畅\AppData\Local\Temp\clawPDF\Spool\589c1f05-ca23-437a-9bc6-292d7725974b\testpage.inf: System.Runtime.InteropServices.ExternalException (0xFFFFFF9C): Ghostscript conversion error
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScriptANY.CallAPI(String[] args)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(IList`1 parameters, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(OutputDevice output, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Jobs.GhostscriptJob.RunJobWork() 
2021-04-21 14:58:59.3107 [Error] clawSoft.clawPDF.Workflow.ConversionWorkflow.RunWorkflow: System.Runtime.InteropServices.ExternalException (0xFFFFFF9C): Ghostscript conversion error
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScriptANY.CallAPI(String[] args)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(IList`1 parameters, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(OutputDevice output, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Jobs.GhostscriptJob.RunJobWork()
   在 clawSoft.clawPDF.Core.Jobs.AbstractJob.RunJob()
   在 clawSoft.clawPDF.Workflow.ConversionWorkflow.DoWorkflowWork()
   在 clawSoft.clawPDF.Workflow.ConversionWorkflow.RunWorkflow() System.Runtime.InteropServices.ExternalException (0xFFFFFF9C): Ghostscript conversion error
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScriptANY.CallAPI(String[] args)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(IList`1 parameters, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Ghostscript.GhostScript.Run(OutputDevice output, String tempOutputFolder)
   在 clawSoft.clawPDF.Core.Jobs.GhostscriptJob.RunJobWork()
   在 clawSoft.clawPDF.Core.Jobs.AbstractJob.RunJob()
   在 clawSoft.clawPDF.Workflow.ConversionWorkflow.DoWorkflowWork()
   在 clawSoft.clawPDF.Workflow.ConversionWorkflow.RunWorkflow()
2021-04-21 14:58:59.3107 [Error] clawSoft.clawPDF.JobRunner.ProcessJob: The job 'CUPS Testpage' terminated at step Convert and did not end successfully.

**Comment by twooclock** [comment]
Hm, looks like Ghostscript issue. Try testing Ghostscript (google it). 
Since ClawPDF relies on [ghostscriptsharp](https://github.com/mephraim/ghostscriptsharp) see issues there. I'm suspecting characters in filename, do you have a chance to enter latin characters for a filename? Also try and save to some other location (not desktop)...?

**Comment by tiandao123456** [comment]
I have used English as the file name and changed the path of the file, but it still has no effect .I will test Ghostscript , thank you.

**Comment by twooclock** [comment]
FYI: My gsdll32.dll and gsdll64.dll are 9.27

**Comment by tiandao123456** [comment]
> FYI: My gsdll32.dll and gsdll64.dll are 9.27
> You might also change ClawPDF logging level to Debug (Program settings/Errors/Log level) and see additional error messages...?

I have found the error , because the previous. PS file is in the path of C: \ \ users \ \ tuchang \ \ appdata \ \ local \ \ temp \ \ clawpdf \ \ spool, now I change my account name to "tuchang" by resetting the computer, and the path changes to C: \ \ users \ \ tuchang \ \ appdata \ \ local \ \ temp \ \ clawpdf \ \ spool, Now it can work normally. The path contains Chinese characters, which will affect the operation of the software. Does ghostscript not support Chinese characters? I still need to study the specific reasons. Thank you for your help!

**Comment by tiandao123456** [comment]
I have found the error , because the previous. PS file is in the path of C: \ \ users \ \ 涂畅 \ \ appdata \ \ local \ \ temp \ \ clawpdf \ \ spool, now I change my account name from "涂畅" to "tuchang" by resetting the computer, and the path changes to C: \ \ users \ \ tuchang \ \ appdata \ \ local \ \ temp \ \ clawpdf \ \ spool, Now it can work normally. The path contains Chinese characters, which will affect the operation of the software. Does ghostscript not support Chinese characters? I still need to study the specific reasons. Thank you for your help!

**Comment by twooclock** [comment]
I'm glad you solved it! I hope this thread helps others with their issues.

**Comment by tiandao123456** [comment]
Thank you for your kindness and help. Thank you！

**Comment by clawsoftware** [comment]
Patched with version 0.8.6
