### ISSUE TITLE
Aks email recipient every time?

### ISSUE THREAD

**Issue by diegomariani** [clawsoftware/clawPDF#48]
Ciao!
You have written a wonderful program!

If I can give you an idea for future development: 
for sending the PDF in an email, allow it to be sent only to a preset recipient. 

You should simply, give the possibility, that the recipient is required every time at the time of printing.

Applications thus possible:
- schools, where students access the same PC with a single account, can send printouts in their own email. 
- Companies, the customer asks you for a copy of the offer, just print it out by entering their email.
- Internet Poit: when someone wants to print, they can do so by sending it to their email
I hope this can be a useful input for you. 
If you implement it, I am the first one who will test it for you.
Greetings
Diego

**Comment by clawsoftware** [comment]
The function was implemented in version 0.9.1
