### ISSUE TITLE
Build is failing when using VS 2019 community edition version on windows 10

### ISSUE THREAD

**Issue by shashankSkydale** [clawsoftware/clawPDF#5]
Getting below errors in VS 2019 community edition, please assist

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x86\SCPDFPRN.ppd" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x64\pscript5.dll" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x86\pscript5.dll" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x64\ps5ui.dll" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x64\SCPDFPRN.ppd" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x86\ps5ui.dll" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x64\pscript.ntf" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x86\pscript.ntf" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x86\pscript.hlp" because it was not found.	clawPDF			
Error		Could not copy the file "E:\VSProjects\clawPDF\clawPDF\clawmon\x64\pscript.hlp" because it was not found.	clawPDF		
```

**Comment by shashankSkydale** [comment]
Please assist.

**Comment by zxdCodeLibrary** [comment]
Me too, I encountered the same problem when compiled this project.
Could anyone help me?

**Comment by zxdCodeLibrary** [comment]
I have fixed this problem,you just need to modify the sub project configure file of clawPDF.

Delete all the copy command lines of the error list fields.

Then you will build succeed.

**Comment by pzw520125** [comment]
@zxdCodeLibrary I have encountered the same problem. Which configuration files should I change?Thank you.

**Comment by brhunt1958** [comment]
shashankSkydale and pzw520125,

In the Solution Explorer, C# Project clawPDF, Folder clawmon, Folders x64 and x86: delete all items under those two folders and build project again.

**Comment by pzw520125** [comment]
@brhunt1958 Thank you.I had a problem reproducing the installation package. The printer was not found. Must the author provide the msi installation package?

**Comment by brhunt1958** [comment]
A followup note here... Deleting those references does allow most of the projects to compile, but it breaks the installer.  So, no way to install/test.  

hessandrew / clawsoftware, can you update the downloadable solution to correct the issues?

Thanks.

Bryan Hunt

**Comment by trentapple** [comment]
I too have encountered these problems discussed here. I was able to get it to build eventually by making modifications, but the installer produced does not successfully setup the printer.

**Comment by twooclock** [comment]
I used [Lessmsi](https://github.com/activescott/lessmsi) to ectract missing files directly from msi, added them to clawmon and it builds! (Also had to copy clawmon.dll to _Build/release/clawmon/x64 for installer to build.)

**Comment by pradeepngupta** [comment]
Any update on this issue, I am still facing the same issue.

**Comment by pradeepngupta** [comment]
@twooclock your advise works... i am able to rebuild the solution, but when i am running, it is giving a popup stating ÇlawPDF is not installed', On continuirng, it is trying to launch SetupHelper but complained that SetupHelper.exe is not found.
Any steps i am missing here.

**Comment by ymeric** [comment]
After updating build target folders for all source projects to align with setup apps expectations, building clawmonui both for Win32 and x64 and copying 64 bit clawmon.dll from the MSI file provided in web site I was able to build setup and install printer in Windows 10. clawmon fails to compile in 64 bit so until that is resolved, this application should not be treated as a complete open source. I'll share if I find the solution for 64 bit compilation issues with clawmon

**Comment by Chirag19** [comment]
clawmon.dll fails to compile in 64 bit only because openssl 64bit folder is messing. Just download it and set at proper location.

**Comment by AlbertoLeon** [comment]
I confirm that using Lessmsi o _clawdPDF_version.msi_ for extracting the missing files works. You will find a clawmon folder that contains exactly what you need in your clawPDF/clawmon folder. Just copy it.

**Comment by HudaKouli** [comment]
> After deleting _Build folder, updating build target folders for all source projects to align with setup app's expectations, building clawmonui both for Win32 and x64 and copying 64 bit clawmon.dll from the MSI file provided in web site I was able to build setup and install printer in Windows 10. clawmon fails to compile in 64 bit so until that is resolved, this application should not be treated as a complete open source. I'll share if I find the solution for 64 bit compilation issues with clawmon

after downlaoding the set up file in visual studio, the files are downloaded but not in exe or msi extension, so I can't set up the printer or add it to printers in windows.
note that I modified the interfaces in claw pdf code and I want to add the new printer to windows. 
is there any way to solve this problem.
