### ISSUE TITLE
Adding a Stamp rotates the print to landscape

### ISSUE THREAD

**Issue by victorromeo** [clawsoftware/clawPDF#55]
Can you please advise if this is a bug? I believe the printer bug is rotating the printed page to landscape whenever a stamp is added to the print.

In addition, I suspect the margins are also impacted, by the rotation transformation.  This can be observed by the cropping of header and footer detail from prints.

**Comment by clawsoftware** [comment]
ClawPDF has an autorotate feature where the page is oriented based on the weight of the text. If the document has very little content, the page will be rotated because the stamp has a higher weight.

You can force the orientation for such cases under "Settings -> PDF -> Page Orientation".
