### ISSUE TITLE
Possible to support printing vector files to SVG?

### ISSUE THREAD

**Issue by mu-arch** [clawsoftware/clawPDF#69]
My workflow requires vector files to send to a laser cutter. I want to support the ability for users to print to a SVG which then gets automatically picked up by my application and printed.

Is this possible? If not, I plan to print to PNG and use a autotracer to convert it back to SVG. Any suggestions appreciated.

**Comment by clawsoftware** [comment]
This functionality was implemented in version 0.9.0.
