### ISSUE TITLE
Problem with App of Microsoft Store of windows 10

### ISSUE THREAD

**Issue by alfredolopez80** [clawsoftware/clawPDF#7]
Hi, friend, 

The virtual printer can printer image, with app of microsoft store of windows 10, for example (Paint 3D, Photo, and Skip & Sketch), However office applications, paint and mail clients and browsers if it works without problem.

Pls, Check

**Comment by LukBukkit** [comment]
Yeah I also can't print using the Windows 10 OneNote application. I click print and no windows of claw pdf pops out.

**Comment by clawsoftware** [comment]
Fixed with version 0.8.5
