### ISSUE TITLE
Possible to save the software and profile registry configuration accessible by all users in the system or domain.

### ISSUE THREAD

**Issue by ahamedrikas** [clawsoftware/clawPDF#71]
Settings and printer profiles are saving under **HKEY_CURRENT_USER** because of which I have to configure profile settings to each and every user in the domain. Is there a way to make it save under **HKEY_LOCAL_MACHINE.** Is there a way to make the profiles usable for all the users in the machine?  

![image](https://user-images.githubusercontent.com/19821766/210320125-ea1a9b75-5611-47ce-879a-6f2861ff84b8.png)

**Comment by clawsoftware** [comment]
As a first solution I have created the parameter Config. This can be used, for example, to distribute the configuration via a logon script. 

Patched with version 0.8.6.
