### ISSUE TITLE
Adding printer

### ISSUE THREAD

**Issue by Elio-art** [clawsoftware/clawPDF#79]
Hello, thank you for this project much appreciated for the time being dedicated
I'm trying to add naming function to the code but when extracting installer setup and installing the software and adding new printer under application settings -> printers, it won't create new printer named clawpdf1 for example. Even though when saving file using clawpdf nothing happen

**Comment by clawsoftware** [comment]
Hello @Elio-art,

Thank you. I don't quite understand what you are trying to achieve. You want to add another printer during the installation, modified the code and now the printer functionality under Application Settings doesn't work anymore?

You can add more printers with "SetupHelper.exe /Printer=Add /Name=ExamplePrinter".

**Comment by Elio-art** [comment]
Thanks for your response
Exactly, I tried to add more printers with setuphelper.exe but unfortunately it didn't run, I don't know if I build the setup in a wrong way.
Is it possible if you could help me by adding a function with naming PDF files (for example starting by number 99999999 and each time when saving new file the number will decrement by 1 ) thanks in advance

**Comment by clawsoftware** [comment]
For the time being, it would probably be best to use the built-in scripting functionality. But in future versions I can create two tokens for name generation like <countup> and <countdown>.
