### ISSUE TITLE
Customize the date format in the document title

### ISSUE THREAD

**Issue by odyodyodys** [clawsoftware/clawPDF#8]
It would be really cool if it was possible to manually set the date format for document titles.
Currently the are two: `DateTime` and `DateTime.yyyyMMddHHmmss`.
Ideally something like the date format of google spreadsheets, where one can build the format they want by adding components.

**Comment by Lovis83854** [comment]
you can edit the "DateTime:yyyyMMddHHmmss" to only show the info you want for ex. i have it set to only show the current date
"DateTime:MM-dd-yy" and i produces 11-5-20
