### ISSUE TITLE
Choosing a printer

### ISSUE THREAD

**Issue by LeenHatem** [clawsoftware/clawPDF#82]
I want to make an interface for choosing the physical printer when printing, so were could I pass the printer name so physical printing is done? what interfaces are used to set values to SelectPrinter (DefaultPrinter, ShowDialog, SelectedPrinter)
Thank you.

**Comment by clawsoftware** [comment]
@LeenHatem Search for Printing.SelectPrinter in https://github.com/clawsoftware/clawPDF/wiki/Scripting-Interface

**Comment by LeenHatem** [comment]
Thank you @clawsoftware 
one other question, how did you send the file to the physical printer, and was it in the postscript or pdf format?

**Comment by clawsoftware** [comment]
@LeenHatem Using the printer monitor `https://github.com/clawsoftware/clawPDF/tree/master/src/clawmon/monitor`. The print job is converted to a Postscript.
