### ISSUE TITLE
Print Spooler Issue

### ISSUE THREAD

**Issue by KalyaniAmbala** [clawsoftware/clawPDF#85]
All the documents to be printed are not showing in spooler at the same time, one by one are coming. How can we do spooling and printing parallelly and can we show all these jobs in spooler?

**Comment by KalyaniAmbala** [comment]
Could you please respond on how to get jobs parallelly in spooler.

**Comment by clawsoftware** [comment]
@KalyaniAmbala I don't quite understand what you mean. Are you talking about the Windows printer queue? What do you want to achieve?

**Comment by clawsoftware** [comment]
The Windows printer queue is independent of clawPDF. This article describes some settings to change the behavior: https://www.techrepublic.com/article/workarounds-for-slow-network-printing/

**Comment by KalyaniAmbala** [comment]
Actually, it is not getting the job immediately into spooler before creating PS file only. 
Can we think like it's an issue of PSCRIPT binaries as these are creating ps files and these are windows printer drivers used in claw pdf?

**Comment by clawsoftware** [comment]
@KalyaniAmbala The PS files are not created until they have entered the Windows spool, since they are processed from there to clawmon and pscript5 (App -> Print -> Spool -> clawmon/pscript5 -> clawpdf -> ghostscript). Are you losing print jobs or what is the exact problem?

**Comment by KalyaniAmbala** [comment]
Hi,

Thanks for your support, My main issue is I am not getting all the print jobs parallelly.
Even if sequentially one after the other, if it is large document taking time to come into the windows spooler, taking time before ps file creation.

But with other vendor printers it's not the issue for same documents, showing all the jobs parallelly in spooler.

Thanks,
Kalyani



Internal

**Comment by clawsoftware** [comment]
@KalyaniAmbala I just tested it with a PDF with 705 pages. Printed with 5 seconds difference from a PDF reader and Chrome. Both are processed at the same time in the spooler for over 1 minute. My test system was Windows 11 and clawPDF 0.9.2.

What application are you printing from and what document is it?

**Comment by KalyaniAmbala** [comment]
I have printed 10 PDF documents. One by one are coming into the spooler and document with more than 2000 pages, it took 90 sec to come into the spooler itself.
After that printing is fast.

My only concern is to get all the 10 documents comes into spooler parallelly otherwise if documents immediately  comes into the spooler after print starts then also fine.


Thanks,
Kalyani


Internal

**Comment by clawsoftware** [comment]
@KalyaniAmbala This is my behavior. You can see in the video that the application (Chrome) prevents parallel printing when I want to print it multiple times from the same tab. As soon as I open the PDF in a new tab and print it, it is sent to the spooler. Here the application is the problem.

https://github.com/clawsoftware/clawPDF/assets/43336352/76219923-1ef6-46bb-bea5-e05f097bf846

**Comment by clawsoftware** [comment]
@KalyaniAmbala In the video you can see a fresh installation of Windows 10 and clawPDF 0.9.2. All standard configuration. There should be no problems with parallel printing unless the application you are printing from does not support it. If you give me more information what the other PDF printers are, I can see if they do anything differently. A video would also be good to analyze the problem better. Thank you!

**Comment by KalyaniAmbala** [comment]
Thanks for your support,

We have used same configuration as like you. We have observed that if the document has more than 1 MB size these pdf documents text is coming in the format of images. 
We have observed that Pscript5 dll is rendering the documents from application and kept in spooler, please see the attached image.
That is why if we have any big documents in the image format, these are taking more time to render and keep in spooler.

As we can see in attached diagram, do we have any rendering plugin's of pscript5 or any updated pscript5.dll for better performance? Could you please help to get this pscript5 dll plugins.

![image](https://github.com/clawsoftware/clawPDF/assets/127513527/68cc732c-f79a-46f1-9528-490958634d97)

**Comment by clawsoftware** [comment]
@KalyaniAmbala Please test this version, because an older version of pscript5 is used and the behavior may be different there: https://github.com/clawsoftware/clawPDF/releases/download/0.8.9/clawPDF_0.8.9_setup.msi

**Comment by KalyaniAmbala** [comment]
Hi,

 As mentioned earlier,  have observed that if the document has more than 1 MB size these pdf documents text is coming in the format of images. This pscript is rendering image format files slowly. If you are able to provide any plugins for pscrit5 it will be very helpful to fix the issue of delay in rendering large files.

Thank you.

**Comment by KalyaniAmbala** [comment]
Could you please check on this once you get time as we stuck-up here?

**Comment by KalyaniAmbala** [comment]
Hi Team,

Thanks for your support, want to run binscope for clawmon.
Could you please share the debug binary of Clawmon dll?


Thanks,
Kalyani




Internal
