### ISSUE TITLE
Installation of 0.9.2 is not upgrading from earlier version

### ISSUE THREAD

**Issue by ThinkEV** [clawsoftware/clawPDF#86]
I had 0.8.4 installed and the installation of 0.9.2 resulted in two versions being installed. Removing 0.8.4 worked, removing 0.9.2 afterwards failed. 

How do I manually remove all installations?
New installations should uninstall earlier versions and do a clean upgrade.

**Comment by ThinkEV** [comment]
Now I managed to uninstall 0.9.2, and installed 0.9.0 again.

When printing one document, It gets printed 6 times!! 
I need to manually repair this, but where do I have to look?

**Comment by clawsoftware** [comment]
@ThinkEV Apologies for the issue. This should not happen in future upgrades. Version 0.8.4 was quite outdated and many stuff has been changed since then.
