### ISSUE TITLE
Application Settings are unresponsive

### ISSUE THREAD

**Issue by zhaotianff** [clawsoftware/clawPDF#87]
OS:Windows 7 sp1 x64
clawPDF version: 0.9.1/0.9.2
version 0.9.0 works fine.

log:
clawSoft.clawPDF.Workflow.ConversionWorkflow.RunWorkflow: System.Windows.Markup.XamlParseException: Initialization of 'System.Windows.Controls.ComboBox' threw an exception. System.Windows.Markup.XamlParseException: Initialization of 'System.Windows.Controls.ComboBox' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework.Aero2, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

**Comment by clawsoftware** [comment]
Thank you for the report @zhaotianff. The installer is unfortunately missing a DLL for Windows 7. Please copy this DLL `https://github.com/clawsoftware/clawPDF/raw/master/src/_Issues/87/PresentationFramework.Aero2.dll` to the folder `C:\Program Files (x86)\clawpdf`. I will include it in the next version.

**Comment by MikeBelov** [comment]
OS:Windows 7 sp1 x86
clawPDF version: 0.9.1/0.9.2
It didn't help me
regsvr32 "C:\Program Files\clawpdf\PresentationFramework.Aero2.dll" 
regsvr32 error: the module was loaded but the entry point was not found

**Comment by zhaotianff** [comment]
> Thank you for the report @zhaotianff. The installer is unfortunately missing a DLL for Windows 7. Please copy this DLL `https://github.com/clawsoftware/clawPDF/raw/master/src/_Issues/87/PresentationFramework.Aero2.dll` to the folder `C:\Program Files (x86)\clawpdf`. I will include it in the next version.

I used the library in your link and still couldn't work. 
I used `C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationFramework.Aero2.dll`，and now it works . Thank you for your reply.

**Comment by zhaotianff** [comment]
> OS:Windows 7 sp1 x86 clawPDF version: 0.9.1/0.9.2 It didn't help me regsvr32 "C:\Program Files\clawpdf\PresentationFramework.Aero2.dll" regsvr32 error: the module was loaded but the entry point was not found

It is not a COM component and does not require calling regsvr32.
just put the PresentationFramework.Aero2.dll in the clawPDF installation path.

**Comment by MikeBelov** [comment]
I did it (download PresentationFramework.Aero2.zip and extract to "C:\Program Files\clawpdf"), but it doesn't help

**Comment by zhaotianff** [comment]
> @zhaotianff @MikeBelov With this version the problem should be solved: https://github.com/clawsoftware/clawPDF/raw/master/src/_MSI/clawPDF_0.9.3_setup.msi
👍
