### ISSUE TITLE
Word > PDF, but EMF images not coming out clearly

### ISSUE THREAD

**Issue by Gabrielquotes2** [clawsoftware/clawPDF#89]
Hi, I'm trying to use Claw to convert a Word document to PDF. The Word document contains an EMF image, which I'd like to come out as a vector. But it [comes out all jagged](https://ibb.co/PQdB71D): whereas when I convert [with Acrobat](https://ibb.co/QjRKHk1), it comes out as a smooth vector as it should.

Can anyone advise me on how to get Claw to achieve the same?

I'm using Windows 10; Claw 0.9.2; Acrobat XI; and Word for Office 365, version 2304.

Thanks!

**Comment by clawsoftware** [comment]
@Gabrielquotes2 Is it possible for you to provide me with an EMF file that you are having problems with?

**Comment by Gabrielquotes2** [comment]
> 

It happens with every EMF I’ve tried, but this one is an example https://www.dropbox.com/s/2jicll7l0t60kiu/oxgoad-quentin-bw.emf?dl=0

**Comment by clawsoftware** [comment]
@Gabrielquotes2 Thank you. The problem occurs when the DPI setting in the printer properties is too low for the file. In Word, click Print Properties when clawPDF is selected. Then click Advanced and set the print quality to 4000 dpi.

With this setting, the problem no longer occurs.

**Comment by clawsoftware** [comment]
@Gabrielquotes2 I just tested it with 2400 DPI. With that, the EMF looks good too. How is it with you?

**Comment by Gabrielquotes2** [comment]
> @Gabrielquotes2 I just tested it with 2400 DPI. With that, the EMF looks good too. How is it with you?

It's certainly looking better but still more jagged than it should be and still more jagged than Acrobat's rendering: https://ibb.co/wsKLtrY
