### ISSUE TITLE
VS 2019 Build Fails due to: clawPDF_setup\clawPDF_setup.vdproj: The application which this project type is based on was not found.

### ISSUE THREAD

**Issue by brhunt1958** [clawsoftware/clawPDF#9]
There should be an additional prerequisite for this project (at least for VS 2019).

The _Microsoft Visual Studio Installer Project_ extension needs to be added to VS 2019 before loading the project solution.

Extensions -> Manage Extensions
Find and Select -> Microsoft Visual Studio Installer Project
Restart VS 2019
Now open solution.

If solution was already opened and built, follow above steps, and after reopening VS 2019 and the clawPDF solution, select the clawPDF_setup project in solution explorer and execute a Project -> Reload.

**Comment by ymeric** [comment]
You need to install Microsoft Visual Studio Installer Projects extension before opening the solution.
![MVSIPE](https://user-images.githubusercontent.com/3727466/98453031-ca34e180-2122-11eb-8121-556360770588.png)
