### ISSUE TITLE
filename template for auto-saving

### ISSUE THREAD

**Issue by ThinkEV** [clawsoftware/clawPDF#91]
With earlier versions the filename template for SAVE was also beeing used for AUTO SAVE.
With 0.9.0 this stopped and AUTO SAVE takes the filename which was supplied by the printing application.

Please re-enable the use of the filename template also for AUTO SAVE.

Maybe merging the SAVE and AUTOSAVE tab would be possible, since they are overlapping.

**Comment by clawsoftware** [comment]
@ThinkEV I cannot reproduce this behavior. Save and autosave must remain separate, as they perform different tasks.

https://github.com/clawsoftware/clawPDF/assets/43336352/a38a1531-0410-4cfa-812b-49e7914a61a5

**Comment by ThinkEV** [comment]
Okay, my fault. It is working fine.
